schema: "classroom50/repo-config/v1"
classroom: "144-web-dev-i"
assignment: "tutorial-3-notes"
owner:
  username: "gtama-e"
  id: 320710023
  accepted_at: "2026-10-06T14:36:16Z"
source:
  owner: "144Fa26"
  owner_id: 299228787
  repo: "tutorial3notes"
  branch: "main"
